### ISSUE TITLE
SSH Key Setup

### ISSUE THREAD

**Issue by jacob-02** [MrSquaare/ssh-setup-action#41]
```
name: ROS2 Humble Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build the workspace
        run: |
          ls
          rm -rf Accio-Messages

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v2
        with:
          host: github.com
          private-key: ${{ secrets.JACOB }}

      - name: Clone repository
        run: git clone git@github.com:Accio-Robotics/Accio-Messages.git
```

This is the GitHub action that I have written. The action is stuck in the Setup SSH step. I have added the private key in secrets in the GitHub repository.
![Screenshot from 2023-07-20 16-53-10](https://github.com/MrSquaare/ssh-setup-action/assets/74947682/4153f158-549e-44ab-8d44-5990551fd26a)
